# Generated by Django 3.1.7 on 2021-04-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210417_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='label',
            new_name='label_plural',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='label_singular',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
