# Generated by Django 3.2.2 on 2021-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20211113_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
